# Generated by Django 5.0.6 on 2024-05-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('skills', models.ManyToManyField(related_name='eployees', to='employee_mgmt.skill')),
            ],
        ),
    ]
