# Generated by Django 5.0.6 on 2024-05-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_mgmt', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(related_name='employees', to='employee_mgmt.skill'),
        ),
    ]
