# Generated by Django 5.0.6 on 2024-05-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_mgmt', '0003_alter_employee_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
