# Generated by Django 5.0.6 on 2024-05-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_mgmt', '0005_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
